-- AI Wardrobe productized Supabase schema
-- Paste this file into Supabase SQL Editor.
-- This version is aligned with the current backend SQLAlchemy models
-- so the backend can point DATABASE_URL directly at Supabase Postgres.

create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
    new.updated_at = timezone('utc', now());
    return new;
end;
$$;

create table if not exists public.users (
    id integer generated by default as identity primary key,
    supabase_user_id varchar(255) null,
    email varchar(255) not null,
    display_name varchar(255) null,
    auth_provider varchar(32) not null default 'supabase',
    wechat_open_id varchar(255) null,
    password_hash varchar(255) not null,
    avatar_url varchar(500) null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

alter table if exists public.users
    add column if not exists supabase_user_id varchar(255);
alter table if exists public.users
    add column if not exists display_name varchar(255);
alter table if exists public.users
    add column if not exists auth_provider varchar(32) not null default 'supabase';
alter table if exists public.users
    add column if not exists wechat_open_id varchar(255);
alter table if exists public.users
    add column if not exists avatar_url varchar(500);
alter table if exists public.users
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

create unique index if not exists ix_users_email on public.users (email);
create unique index if not exists ix_users_supabase_user_id on public.users (supabase_user_id);
create unique index if not exists ix_users_wechat_open_id on public.users (wechat_open_id);

insert into public.users (
    supabase_user_id,
    email,
    display_name,
    auth_provider,
    password_hash,
    avatar_url,
    created_at
)
select
    au.id::text,
    au.email,
    coalesce(
        au.raw_user_meta_data ->> 'full_name',
        au.raw_user_meta_data ->> 'name',
        split_part(coalesce(au.email, ''), '@', 1),
        '新用户'
    ),
    'supabase',
    'supabase-managed',
    coalesce(au.raw_user_meta_data ->> 'avatar_url', au.raw_user_meta_data ->> 'picture'),
    coalesce(au.created_at, timezone('utc', now()))
from auth.users au
where au.email is not null
on conflict (email) do update
set
    supabase_user_id = excluded.supabase_user_id,
    display_name = coalesce(excluded.display_name, public.users.display_name),
    auth_provider = 'supabase',
    avatar_url = coalesce(excluded.avatar_url, public.users.avatar_url),
    updated_at = timezone('utc', now());

create table if not exists public.categories (
    id integer generated by default as identity primary key,
    name varchar(120) not null,
    icon varchar(120) null,
    sort_order integer not null default 0,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create unique index if not exists ix_categories_name on public.categories (name);

insert into public.categories (name, icon, sort_order)
values
    ('tops', 'shirt', 10),
    ('bottoms', 'trousers', 20),
    ('outerwear', 'coat', 30),
    ('dresses', 'dress', 40),
    ('shoes', 'shoe', 50),
    ('accessories', 'bag', 60)
on conflict (name) do update
set
    icon = excluded.icon,
    sort_order = excluded.sort_order,
    updated_at = timezone('utc', now());

create table if not exists public.tags (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id) on delete cascade,
    name varchar(120) not null,
    color varchar(32) null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_tags_user_id on public.tags (user_id);
create index if not exists ix_tags_name on public.tags (name);

create table if not exists public.avatars_3d (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id) on delete cascade,
    model_url varchar(500) null,
    source_images jsonb not null default '[]'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_avatars_3d_user_id on public.avatars_3d (user_id);

create table if not exists public.clothing_items (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id) on delete cascade,
    owner_supabase_user_id text null,
    owner_email text null,
    name varchar(255) not null,
    category varchar(64) not null,
    slot varchar(64) not null,
    color varchar(64) not null,
    brand varchar(120) null,
    image_url varchar(500) null,
    processed_image_url varchar(500) null,
    image_backup_url text null,
    processed_image_backup_url text null,
    tags jsonb not null default '[]'::jsonb,
    occasions jsonb not null default '[]'::jsonb,
    style_notes text null,
    created_at timestamptz not null default timezone('utc', now()),
    last_synced_at timestamptz null,
    synced_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

do $$
begin
    begin
        alter table public.clothing_items alter column id add generated by default as identity;
    exception
        when duplicate_object then null;
        when object_not_in_prerequisite_state then null;
        when invalid_table_definition then null;
    end;
end;
$$;

do $$
declare
    seq_name text;
begin
    seq_name := pg_get_serial_sequence('public.clothing_items', 'id');
    if seq_name is not null then
        execute format(
            'select setval(%L, coalesce((select max(id) from public.clothing_items), 0) + 1, false)',
            seq_name
        );
    end if;
end;
$$;

alter table if exists public.clothing_items
    add column if not exists owner_supabase_user_id text;
alter table if exists public.clothing_items
    add column if not exists owner_email text;
alter table if exists public.clothing_items
    add column if not exists image_backup_url text;
alter table if exists public.clothing_items
    add column if not exists processed_image_backup_url text;
alter table if exists public.clothing_items
    add column if not exists last_synced_at timestamptz;
alter table if exists public.clothing_items
    add column if not exists synced_at timestamptz not null default timezone('utc', now());
alter table if exists public.clothing_items
    add column if not exists updated_at timestamptz not null default timezone('utc', now());

create index if not exists ix_clothing_items_user_id on public.clothing_items (user_id);
create index if not exists ix_clothing_items_name on public.clothing_items (name);
create index if not exists ix_clothing_items_category on public.clothing_items (category);
create index if not exists ix_clothing_items_slot on public.clothing_items (slot);
create index if not exists ix_clothing_items_created_at on public.clothing_items (created_at desc);
create index if not exists clothing_items_owner_supabase_user_id_idx on public.clothing_items (owner_supabase_user_id);

create table if not exists public.outfits (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id) on delete cascade,
    name varchar(255) not null,
    occasion varchar(120) null,
    style varchar(120) null,
    cover_image varchar(500) null,
    ai_generated boolean not null default true,
    item_ids jsonb not null default '[]'::jsonb,
    reasoning text null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_outfits_user_id on public.outfits (user_id);
create index if not exists ix_outfits_created_at on public.outfits (created_at desc);

create table if not exists public.outfit_recommendations (
    id integer generated by default as identity primary key,
    user_id integer null references public.users(id) on delete cascade,
    prompt text not null,
    result_outfit_ids jsonb not null default '[]'::jsonb,
    feedback text null,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_outfit_recommendations_user_id on public.outfit_recommendations (user_id);

create table if not exists public.style_profiles (
    id integer generated by default as identity primary key,
    user_id integer not null unique references public.users(id) on delete cascade,
    favorite_colors jsonb not null default '[]'::jsonb,
    avoid_colors jsonb not null default '[]'::jsonb,
    favorite_silhouettes jsonb not null default '[]'::jsonb,
    avoid_silhouettes jsonb not null default '[]'::jsonb,
    style_keywords jsonb not null default '[]'::jsonb,
    dislike_keywords jsonb not null default '[]'::jsonb,
    commute_profile varchar(120) null,
    comfort_priorities jsonb not null default '[]'::jsonb,
    wardrobe_rules jsonb not null default '[]'::jsonb,
    personal_note text null,
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_style_profiles_user_id on public.style_profiles (user_id);

create table if not exists public.clothing_memory_cards (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    item_id integer not null unique references public.clothing_items(id) on delete cascade,
    highlights jsonb not null default '[]'::jsonb,
    avoid_contexts jsonb not null default '[]'::jsonb,
    care_status varchar(64) not null default 'fresh',
    care_note text null,
    season_tags jsonb not null default '[]'::jsonb,
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_clothing_memory_cards_user_id on public.clothing_memory_cards (user_id);
create index if not exists ix_clothing_memory_cards_item_id on public.clothing_memory_cards (item_id);

create table if not exists public.wear_logs (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    outfit_id integer null references public.outfits(id) on delete set null,
    outfit_name varchar(255) null,
    item_ids jsonb not null default '[]'::jsonb,
    occasion varchar(120) null,
    period varchar(32) not null default 'all-day',
    location_label varchar(255) null,
    feedback_note text null,
    worn_on timestamptz not null default timezone('utc', now())
);

create index if not exists ix_wear_logs_user_id on public.wear_logs (user_id);
create index if not exists ix_wear_logs_worn_on on public.wear_logs (worn_on desc);

create table if not exists public.recommendation_signals (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    prompt text null,
    scene varchar(120) null,
    action varchar(64) not null,
    item_ids jsonb not null default '[]'::jsonb,
    feedback_note text null,
    metadata_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_recommendation_signals_user_id on public.recommendation_signals (user_id);
create index if not exists ix_recommendation_signals_action on public.recommendation_signals (action);
create index if not exists ix_recommendation_signals_created_at on public.recommendation_signals (created_at desc);

create table if not exists public.assistant_tasks (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    task_type varchar(120) not null,
    status varchar(64) not null default 'queued',
    input_payload jsonb not null default '{}'::jsonb,
    result_payload jsonb null,
    error_message text null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    completed_at timestamptz null
);

create index if not exists ix_assistant_tasks_user_id on public.assistant_tasks (user_id);
create index if not exists ix_assistant_tasks_task_type on public.assistant_tasks (task_type);
create index if not exists ix_assistant_tasks_status on public.assistant_tasks (status);
create index if not exists ix_assistant_tasks_created_at on public.assistant_tasks (created_at desc);

create table if not exists public.auth_session_tokens (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    provider varchar(32) not null default 'local',
    access_token_hash varchar(128) not null,
    refresh_token_hash varchar(128) not null,
    expires_at timestamptz not null,
    refresh_expires_at timestamptz not null,
    device_label varchar(120) null,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now()),
    revoked_at timestamptz null
);

create unique index if not exists ix_auth_session_tokens_access_token_hash on public.auth_session_tokens (access_token_hash);
create unique index if not exists ix_auth_session_tokens_refresh_token_hash on public.auth_session_tokens (refresh_token_hash);
create index if not exists ix_auth_session_tokens_user_id on public.auth_session_tokens (user_id);

create table if not exists public.password_reset_tokens (
    id integer generated by default as identity primary key,
    user_id integer not null references public.users(id) on delete cascade,
    token_hash varchar(128) not null,
    expires_at timestamptz not null,
    created_at timestamptz not null default timezone('utc', now()),
    used_at timestamptz null
);

create unique index if not exists ix_password_reset_tokens_token_hash on public.password_reset_tokens (token_hash);
create index if not exists ix_password_reset_tokens_user_id on public.password_reset_tokens (user_id);

create table if not exists public.experience_user_states (
    id integer generated by default as identity primary key,
    user_id integer not null unique references public.users(id) on delete cascade,
    state_json jsonb not null default '{}'::jsonb,
    created_at timestamptz not null default timezone('utc', now()),
    updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists ix_experience_user_states_user_id on public.experience_user_states (user_id);

do $$
declare
    tbl text;
begin
    foreach tbl in array array[
        'users',
        'categories',
        'tags',
        'avatars_3d',
        'clothing_items',
        'style_profiles',
        'clothing_memory_cards',
        'assistant_tasks',
        'auth_session_tokens',
        'experience_user_states'
    ]
    loop
        execute format('drop trigger if exists set_%I_updated_at on public.%I', tbl, tbl);
        execute format(
            'create trigger set_%I_updated_at before update on public.%I for each row execute function public.set_updated_at()',
            tbl,
            tbl
        );
    end loop;
end;
$$;

insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
    'wardrobe-assets',
    'wardrobe-assets',
    true,
    10485760,
    array['image/png', 'image/jpeg', 'image/webp', 'image/jpg']
)
on conflict (id) do update
set
    public = excluded.public,
    file_size_limit = excluded.file_size_limit,
    allowed_mime_types = excluded.allowed_mime_types;

comment on table public.experience_user_states is
'Stores the experience page state that used to live in experience_state.json. With DATABASE_URL pointed at Supabase Postgres, these states are persisted in Supabase.';
